[versions]
avro = "1.12.1"
commonsCli = "1.11.0"
# Dependencies
confluent = "8.1.1"
findbug = "3.0.2"
greenmail = "2.1.8"
jackson = "2.21"
jacksonModuleKotlin = "2.21.1"
javaMail = "2.1.5"
junit-jupiter = "5.10.1"
kafka = "8.1.1-ce"
# Project and Plugins
kotlin = "2.2.10"
ksoup = "0.2.6"
log4j = "2.23.1"
mockito = "5.21.0"
radarCommons = "1.2.4"
radarSchemas = "0.8.15"
slf4j = "2.0.17"
versionCatalogUpdate = "0.8.5"

[libraries]
avro = { module = "org.apache.avro:avro", version.ref = "avro" }
commons-cli = { module = "commons-cli:commons-cli", version.ref = "commonsCli" }
greenmail = { module = "com.icegreen:greenmail", version.ref = "greenmail" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jacksonModuleKotlin" }
jakarta-mail = { module = "jakarta.mail:jakarta.mail-api", version.ref = "javaMail" }
# Utilities
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "findbug" }
# Kafka & Confluent
kafka-streams = { module = "org.apache.kafka:kafka-streams", version.ref = "kafka" }
kafka-streams-avro-serde = { module = "io.confluent:kafka-streams-avro-serde", version.ref = "confluent" }
# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
ksoup-network = { module = "com.fleeksoft.ksoup:ksoup-network", version.ref = "ksoup" }
# Logging
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
# RADAR-Base
radar-commons = { module = "org.radarbase:radar-commons", version.ref = "radarCommons" }
radar-commons-server = { module = "org.radarbase:radar-commons-server", version.ref = "radarCommons" }
radar-commons-testing = { module = "org.radarbase:radar-commons-testing", version.ref = "radarCommons" }
radar-schemas-commons = { module = "org.radarbase:radar-schemas-commons", version.ref = "radarSchemas" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-jupiter" }

[plugins]
radar-dependency-management = { id = "org.radarbase.radar-dependency-management", version.ref = "radarCommons" }
radar-kotlin = { id = "org.radarbase.radar-kotlin", version.ref = "radarCommons" }
radar-publishing = { id = "org.radarbase.radar-publishing", version.ref = "radarCommons" }
radar-root-project = { id = "org.radarbase.radar-root-project", version.ref = "radarCommons" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[bundles]
ksoup = [
    "ksoup",
    "ksoup-network",
]
