apply from: 'gradle/test.gradle'

tasks.register('downloadTestDependencies') {
    description "Pre-downloads *most* dependencies"
    configurations.compileClasspath.files
    configurations.testCompileClasspath.files
    configurations.integrationTestCompileClasspath.files
    configurations.integrationTestRuntimeClasspath.files
}
