#!/bin/sh

set -e

# Busy waiting loop that waits untill all topic are available
echo "===> Waiting for RADAR-CNS topics ... "

# Check if variables exist
if [ -n "$KAFKA_SCHEMA_REGISTRY" ]; then
  max_timeout=32

  tries=10
  timeout=1
  while true; do
      if [ $(curl -s "${KAFKA_SCHEMA_REGISTRY}/subjects" | wc -c) -ge 2 ]; then
          break
      fi
      tries=$((tries - 1))
      if [ $tries -eq 0 ]; then
          echo "FAILED TO REACH SCHEMA REGISTRY. SCHEMAS NOT REGISTERED."
          exit 6
      fi
      echo "Failed to reach schema registry. Retrying in ${timeout} seconds."
      sleep $timeout
      if [ $timeout -lt $max_timeout ]; then
          timeout=$((timeout * 2))
      fi
  done

  echo "Kafka is available. Ready to go!"
fi

RADAR_BACKEND_CONFIG="${RADAR_BACKEND_CONFIG:-/etc/radar.yml}"

# Start streams
echo "===> Starting " "$@" "...."
exec radar-backend -c "$RADAR_BACKEND_CONFIG" "$@"
