/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.stream.phone;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TemporaryPackageKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5825691401492875312L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TemporaryPackageKey\",\"namespace\":\"org.radarcns.stream.phone\",\"fields\":[{\"name\":\"projectId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Project ID.\"},{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"User ID.\"},{\"name\":\"sourceId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Source ID.\"},{\"name\":\"packageName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Package name.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TemporaryPackageKey> ENCODER =
      new BinaryMessageEncoder<TemporaryPackageKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TemporaryPackageKey> DECODER =
      new BinaryMessageDecoder<TemporaryPackageKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TemporaryPackageKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TemporaryPackageKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TemporaryPackageKey>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TemporaryPackageKey to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TemporaryPackageKey from a ByteBuffer. */
  public static TemporaryPackageKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Project ID. */
  @Deprecated public java.lang.String projectId;
  /** User ID. */
  @Deprecated public java.lang.String userId;
  /** Source ID. */
  @Deprecated public java.lang.String sourceId;
  /** Package name. */
  @Deprecated public java.lang.String packageName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TemporaryPackageKey() {}

  /**
   * All-args constructor.
   * @param projectId Project ID.
   * @param userId User ID.
   * @param sourceId Source ID.
   * @param packageName Package name.
   */
  public TemporaryPackageKey(java.lang.String projectId, java.lang.String userId, java.lang.String sourceId, java.lang.String packageName) {
    this.projectId = projectId;
    this.userId = userId;
    this.sourceId = sourceId;
    this.packageName = packageName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return projectId;
    case 1: return userId;
    case 2: return sourceId;
    case 3: return packageName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: projectId = (java.lang.String)value$; break;
    case 1: userId = (java.lang.String)value$; break;
    case 2: sourceId = (java.lang.String)value$; break;
    case 3: packageName = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'projectId' field.
   * @return Project ID.
   */
  public java.lang.String getProjectId() {
    return projectId;
  }

  /**
   * Sets the value of the 'projectId' field.
   * Project ID.
   * @param value the value to set.
   */
  public void setProjectId(java.lang.String value) {
    this.projectId = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return User ID.
   */
  public java.lang.String getUserId() {
    return userId;
  }

  /**
   * Sets the value of the 'userId' field.
   * User ID.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'sourceId' field.
   * @return Source ID.
   */
  public java.lang.String getSourceId() {
    return sourceId;
  }

  /**
   * Sets the value of the 'sourceId' field.
   * Source ID.
   * @param value the value to set.
   */
  public void setSourceId(java.lang.String value) {
    this.sourceId = value;
  }

  /**
   * Gets the value of the 'packageName' field.
   * @return Package name.
   */
  public java.lang.String getPackageName() {
    return packageName;
  }

  /**
   * Sets the value of the 'packageName' field.
   * Package name.
   * @param value the value to set.
   */
  public void setPackageName(java.lang.String value) {
    this.packageName = value;
  }

  /**
   * Creates a new TemporaryPackageKey RecordBuilder.
   * @return A new TemporaryPackageKey RecordBuilder
   */
  public static org.radarcns.stream.phone.TemporaryPackageKey.Builder newBuilder() {
    return new org.radarcns.stream.phone.TemporaryPackageKey.Builder();
  }

  /**
   * Creates a new TemporaryPackageKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TemporaryPackageKey RecordBuilder
   */
  public static org.radarcns.stream.phone.TemporaryPackageKey.Builder newBuilder(org.radarcns.stream.phone.TemporaryPackageKey.Builder other) {
    return new org.radarcns.stream.phone.TemporaryPackageKey.Builder(other);
  }

  /**
   * Creates a new TemporaryPackageKey RecordBuilder by copying an existing TemporaryPackageKey instance.
   * @param other The existing instance to copy.
   * @return A new TemporaryPackageKey RecordBuilder
   */
  public static org.radarcns.stream.phone.TemporaryPackageKey.Builder newBuilder(org.radarcns.stream.phone.TemporaryPackageKey other) {
    return new org.radarcns.stream.phone.TemporaryPackageKey.Builder(other);
  }

  /**
   * RecordBuilder for TemporaryPackageKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TemporaryPackageKey>
    implements org.apache.avro.data.RecordBuilder<TemporaryPackageKey> {

    /** Project ID. */
    private java.lang.String projectId;
    /** User ID. */
    private java.lang.String userId;
    /** Source ID. */
    private java.lang.String sourceId;
    /** Package name. */
    private java.lang.String packageName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.stream.phone.TemporaryPackageKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.projectId)) {
        this.projectId = data().deepCopy(fields()[0].schema(), other.projectId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema(), other.userId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sourceId)) {
        this.sourceId = data().deepCopy(fields()[2].schema(), other.sourceId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.packageName)) {
        this.packageName = data().deepCopy(fields()[3].schema(), other.packageName);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TemporaryPackageKey instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.stream.phone.TemporaryPackageKey other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.projectId)) {
        this.projectId = data().deepCopy(fields()[0].schema(), other.projectId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema(), other.userId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sourceId)) {
        this.sourceId = data().deepCopy(fields()[2].schema(), other.sourceId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.packageName)) {
        this.packageName = data().deepCopy(fields()[3].schema(), other.packageName);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'projectId' field.
      * Project ID.
      * @return The value.
      */
    public java.lang.String getProjectId() {
      return projectId;
    }

    /**
      * Sets the value of the 'projectId' field.
      * Project ID.
      * @param value The value of 'projectId'.
      * @return This builder.
      */
    public org.radarcns.stream.phone.TemporaryPackageKey.Builder setProjectId(java.lang.String value) {
      validate(fields()[0], value);
      this.projectId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'projectId' field has been set.
      * Project ID.
      * @return True if the 'projectId' field has been set, false otherwise.
      */
    public boolean hasProjectId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'projectId' field.
      * Project ID.
      * @return This builder.
      */
    public org.radarcns.stream.phone.TemporaryPackageKey.Builder clearProjectId() {
      projectId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * User ID.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return userId;
    }

    /**
      * Sets the value of the 'userId' field.
      * User ID.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public org.radarcns.stream.phone.TemporaryPackageKey.Builder setUserId(java.lang.String value) {
      validate(fields()[1], value);
      this.userId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * User ID.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'userId' field.
      * User ID.
      * @return This builder.
      */
    public org.radarcns.stream.phone.TemporaryPackageKey.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'sourceId' field.
      * Source ID.
      * @return The value.
      */
    public java.lang.String getSourceId() {
      return sourceId;
    }

    /**
      * Sets the value of the 'sourceId' field.
      * Source ID.
      * @param value The value of 'sourceId'.
      * @return This builder.
      */
    public org.radarcns.stream.phone.TemporaryPackageKey.Builder setSourceId(java.lang.String value) {
      validate(fields()[2], value);
      this.sourceId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'sourceId' field has been set.
      * Source ID.
      * @return True if the 'sourceId' field has been set, false otherwise.
      */
    public boolean hasSourceId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'sourceId' field.
      * Source ID.
      * @return This builder.
      */
    public org.radarcns.stream.phone.TemporaryPackageKey.Builder clearSourceId() {
      sourceId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'packageName' field.
      * Package name.
      * @return The value.
      */
    public java.lang.String getPackageName() {
      return packageName;
    }

    /**
      * Sets the value of the 'packageName' field.
      * Package name.
      * @param value The value of 'packageName'.
      * @return This builder.
      */
    public org.radarcns.stream.phone.TemporaryPackageKey.Builder setPackageName(java.lang.String value) {
      validate(fields()[3], value);
      this.packageName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'packageName' field has been set.
      * Package name.
      * @return True if the 'packageName' field has been set, false otherwise.
      */
    public boolean hasPackageName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'packageName' field.
      * Package name.
      * @return This builder.
      */
    public org.radarcns.stream.phone.TemporaryPackageKey.Builder clearPackageName() {
      packageName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TemporaryPackageKey build() {
      try {
        TemporaryPackageKey record = new TemporaryPackageKey();
        record.projectId = fieldSetFlags()[0] ? this.projectId : (java.lang.String) defaultValue(fields()[0]);
        record.userId = fieldSetFlags()[1] ? this.userId : (java.lang.String) defaultValue(fields()[1]);
        record.sourceId = fieldSetFlags()[2] ? this.sourceId : (java.lang.String) defaultValue(fields()[2]);
        record.packageName = fieldSetFlags()[3] ? this.packageName : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TemporaryPackageKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<TemporaryPackageKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TemporaryPackageKey>
    READER$ = (org.apache.avro.io.DatumReader<TemporaryPackageKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
