/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarbase.stream.phone

import org.apache.avro.AvroRuntimeException
import org.apache.avro.Schema
import org.apache.avro.data.RecordBuilder
import org.apache.avro.message.BinaryMessageDecoder
import org.apache.avro.message.BinaryMessageEncoder
import org.apache.avro.message.SchemaStore
import org.apache.avro.specific.SpecificData
import org.apache.avro.specific.SpecificRecord
import org.apache.avro.specific.SpecificRecordBase
import org.apache.avro.specific.SpecificRecordBuilderBase
import java.io.IOException
import java.nio.ByteBuffer

@Suppress("all")
class TemporaryPackageKey : SpecificRecordBase, SpecificRecord {
    @JvmField var projectId: String? = null
    @JvmField var userId: String? = null
    @JvmField var sourceId: String? = null
    @JvmField var packageName: String? = null

    constructor()

    constructor(projectId: String?, userId: String?, sourceId: String?, packageName: String?) {
        this.projectId = projectId
        this.userId = userId
        this.sourceId = sourceId
        this.packageName = packageName
    }

    override fun getSchema(): Schema = SCHEMA

    override fun get(field: Int): Any? {
        return when (field) {
            0 -> projectId
            1 -> userId
            2 -> sourceId
            3 -> packageName
            else -> throw AvroRuntimeException("Bad index")
        }
    }

    override fun put(field: Int, value: Any?) {
        when (field) {
            0 -> projectId = value as String?
            1 -> userId = value as String?
            2 -> sourceId = value as String?
            3 -> packageName = value as String?
            else -> throw AvroRuntimeException("Bad index")
        }
    }

    @Throws(IOException::class)
    fun toByteBuffer(): ByteBuffer = ENCODER.encode(this)

    companion object {
        private const val serialVersionUID = 5825691401492875312L
        @JvmField
        val SCHEMA: Schema = Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TemporaryPackageKey\",\"namespace\":\"org.radarbase.stream.phone\",\"fields\":[{\"name\":\"projectId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Project ID.\"},{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"User ID.\"},{\"name\":\"sourceId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Source ID.\"},{\"name\":\"packageName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Package name.\"}]}")
        
        @JvmStatic
        fun getClassSchema(): Schema = SCHEMA

        private val MODEL = SpecificData()
        private val ENCODER = BinaryMessageEncoder<TemporaryPackageKey>(MODEL, SCHEMA)
        private val DECODER = BinaryMessageDecoder<TemporaryPackageKey>(MODEL, SCHEMA)

        @JvmStatic
        fun getDecoder(): BinaryMessageDecoder<TemporaryPackageKey> = DECODER

        @JvmStatic
        fun createDecoder(resolver: SchemaStore): BinaryMessageDecoder<TemporaryPackageKey> {
            return BinaryMessageDecoder(MODEL, SCHEMA, resolver)
        }

        @JvmStatic
        @Throws(IOException::class)
        fun fromByteBuffer(b: ByteBuffer): TemporaryPackageKey = DECODER.decode(b)

        @JvmStatic
        fun newBuilder(): Builder = Builder()

        @JvmStatic
        fun newBuilder(other: Builder): Builder = Builder(other)

        @JvmStatic
        fun newBuilder(other: TemporaryPackageKey): Builder = Builder(other)
    }

    class Builder : SpecificRecordBuilderBase<TemporaryPackageKey>, RecordBuilder<TemporaryPackageKey> {
        private var projectId: String? = null
        private var userId: String? = null
        private var sourceId: String? = null
        private var packageName: String? = null

        constructor() : super(SCHEMA)

        constructor(other: Builder) : super(other)

        constructor(other: TemporaryPackageKey) : super(SCHEMA)

        fun getProjectId(): String? = projectId
        fun setProjectId(value: String?): Builder {
            validate(fields()[0], value)
            this.projectId = value
            fieldSetFlags()[0] = true
            return this
        }
        fun hasProjectId(): Boolean = fieldSetFlags()[0]
        fun clearProjectId(): Builder {
            projectId = null
            fieldSetFlags()[0] = false
            return this
        }

        fun getUserId(): String? = userId
        fun setUserId(value: String?): Builder {
            validate(fields()[1], value)
            this.userId = value
            fieldSetFlags()[1] = true
            return this
        }
        fun hasUserId(): Boolean = fieldSetFlags()[1]
        fun clearUserId(): Builder {
            userId = null
            fieldSetFlags()[1] = false
            return this
        }

        fun getSourceId(): String? = sourceId
        fun setSourceId(value: String?): Builder {
            validate(fields()[2], value)
            this.sourceId = value
            fieldSetFlags()[2] = true
            return this
        }
        fun hasSourceId(): Boolean = fieldSetFlags()[2]
        fun clearSourceId(): Builder {
            sourceId = null
            fieldSetFlags()[2] = false
            return this
        }

        fun getPackageName(): String? = packageName
        fun setPackageName(value: String?): Builder {
            validate(fields()[3], value)
            this.packageName = value
            fieldSetFlags()[3] = true
            return this
        }
        fun hasPackageName(): Boolean = fieldSetFlags()[3]
        fun clearPackageName(): Builder {
            packageName = null
            fieldSetFlags()[3] = false
            return this
        }

        override fun build(): TemporaryPackageKey {
            return try {
                val record = TemporaryPackageKey()
                record.projectId = if (fieldSetFlags()[0]) this.projectId else defaultValue(fields()[0]) as String?
                record.userId = if (fieldSetFlags()[1]) this.userId else defaultValue(fields()[1]) as String?
                record.sourceId = if (fieldSetFlags()[2]) this.sourceId else defaultValue(fields()[2]) as String?
                record.packageName = if (fieldSetFlags()[3]) this.packageName else defaultValue(fields()[3]) as String?
                record
            } catch (e: Exception) {
                throw AvroRuntimeException(e)
            }
        }
    }
}
