name: Snyk test
on:
  pull_request:
    branches: [ master, dev ]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          DEBUG: '*snyk*'
        with:
          args: --all-projects --configuration-matching='^runtimeClasspath$' --severity-threshold=high --policy-path=$PWD/.snyk
