name: Snyk test
on:
  pull_request:
    branches: [ master, dev ]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: snyk/actions/setup@master
        with:
          snyk-version: v1.1032.0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          DEBUG: '*snyk*'
        run: >
          snyk test
          --all-projects
          --configuration-matching='^runtimeClasspath$'
          --org=radar-base
          --policy-path=$PWD/.snyk
          --severity-threshold=high